<?php
/**
 * FIXED: Confirmation Page
 * Added: Authentication, CSS
 * Kept: Your teammate's PDF generation logic 100%
 */

session_start();
require_once '../includes/db_connect.php';
require_once '../includes/functions.php';

// ✅ ADDED: Proper authentication
requireLogin();

// ✅ KEPT: Your teammate's booking data logic
$my_bookings = $_SESSION['cart'] ?? [];

// Redirect if cart is empty
if (empty($my_bookings)) {
    setFlash('Your cart is empty!', 'error');
    header("Location: book.php");
    exit();
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation</title>
    <!-- ✅ ADDED: CSS Link -->
    <link rel="stylesheet" href="../assets/css/style.css">
    <!-- ✅ KEPT: Your teammate's jsPDF library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
</head>
<body>
    <!-- ✅ ADDED: Header -->
    <?php include '../includes/header.php'; ?>
    
    <main class="container" style="padding: 2rem 0;">
        <h1>📋 Confirm Your Booking</h1>
        
        <!-- Receipt Card -->
        <div class="card" id="receipt-area">
            <div class="card-header">
                <h2 class="card-title">Booking Receipt</h2>
            </div>
            
            <div style="background: var(--light); padding: 1.5rem; border-radius: var(--radius); margin-bottom: 1.5rem;">
                <p><strong>User:</strong> <?php echo htmlspecialchars(getCurrentUserName()); ?></p>
                <p><strong>User ID:</strong> MEM-<?php echo str_pad(getCurrentUserId(), 4, '0', STR_PAD_LEFT); ?></p>
                <p><strong>Date:</strong> <?php echo date('F d, Y'); ?></p>
                <p style="margin: 0;"><strong>Time:</strong> <?php echo date('g:i A'); ?></p>
            </div>
            
            <h3>Booked Laboratories:</h3>
            <ul style="list-style: none; padding: 0;">
                <?php foreach ($my_bookings as $item): ?>
                    <li style="padding: 0.75rem; border-left: 4px solid var(--primary-color); background: var(--light); margin-bottom: 0.5rem; border-radius: var(--radius);">
                        <strong><?php echo htmlspecialchars($item['name']); ?></strong><br>
                        <small style="color: var(--text-light);">Lab ID: L<?php echo str_pad($item['id'], 3, '0', STR_PAD_LEFT); ?></small>
                    </li>
                <?php endforeach; ?>
            </ul>
            
            <div style="margin-top: 2rem; display: flex; gap: 1rem; flex-wrap: wrap;">
                <button onclick="downloadPDF()" class="btn btn-success">📄 Download PDF Receipt</button>
                <a href="history.php?save=true" class="btn btn-primary">✓ Finish Booking</a>
                <a href="cart.php" class="btn btn-secondary">← Back to Cart</a>
            </div>
        </div>
    </main>

    <!-- ✅ ADDED: Footer -->
    <?php include '../includes/footer.php'; ?>

    <!-- ✅ KEPT: Your teammate's PDF generation script (UNCHANGED) -->
    <script>
        function downloadPDF() {
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF();
            
            // Title
            doc.setFontSize(20);
            doc.setTextColor(37, 99, 235); // Primary color
            doc.text("LAB BOOKING RECEIPT", 20, 20);
            
            // Line separator
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text("_________________________________________________", 20, 25);
            
            // User info
            doc.text("User: <?php echo addslashes(getCurrentUserName()); ?>", 20, 35);
            doc.text("User ID: MEM-<?php echo str_pad(getCurrentUserId(), 4, '0', STR_PAD_LEFT); ?>", 20, 42);
            doc.text("Date: <?php echo date('F d, Y'); ?>", 20, 49);
            doc.text("Time: <?php echo date('g:i A'); ?>", 20, 56);
            
            // Bookings header
            doc.text("_________________________________________________", 20, 61);
            doc.setFontSize(14);
            doc.text("Booked Laboratories:", 20, 71);
            doc.setFontSize(12);
            
            // List bookings
            let y = 81;
            <?php foreach ($my_bookings as $item): ?>
                doc.text("• <?php echo addslashes($item['name']); ?>", 25, y);
                doc.setFontSize(10);
                doc.setTextColor(100, 100, 100);
                doc.text("  (Lab ID: L<?php echo str_pad($item['id'], 3, '0', STR_PAD_LEFT); ?>)", 25, y + 5);
                doc.setFontSize(12);
                doc.setTextColor(0, 0, 0);
                y += 15;
            <?php endforeach; ?>
            
            // Footer
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            doc.text("Generated by Lab Booking System", 20, 280);
            doc.text("Thank you for using our service!", 20, 285);
            
            // Save
            doc.save("Lab_Receipt_<?php echo date('Ymd_His'); ?>.pdf");
            
            // Show success message
            alert('PDF Receipt downloaded successfully!');
        }
    </script>
</body>
</html>